### ISSUE TITLE
Cabal 1.24.0.1 release

### ISSUE THREAD

**Issue by Mistuke** [haskell/cabal-website#1]
Sorry if this isn't the right place. I'm just not sure where this should be sent.

The download page https://www.haskell.org/cabal/download.html has me slightly confused about `1.24.0.1`. It says it's released but there are only source tarballs.

All the binaries point to the `1.24.0.0` release. So is the new version an in-place upgrade to `1.24.0.0`? Or are there just no binary releases and a new user should download `1.24.0.0` and upgrade to `1.24.0.1`?

**Comment by hvr** [comment]
It just means that we don't have built official binaries  for 1.24.0.1 yet ... and yes, in the meantime you'll have to build those yourself (either bootstrap directly via the boostrapping script, or by using a preexisting `cabal` executable)

**Comment by Mistuke** [comment]
Fair enough, guess I was just too impatient :)

**Comment by 23Skidoo** [comment]
Closing, since the 1.24.0.2 release is now out [and the binaries are available](https://www.haskell.org/cabal/download.html).
