### ISSUE TITLE
Downloads page needs update for 3.6.2.0 release

### ISSUE THREAD

**Issue by gbaz** [haskell/cabal-website#28]

**Comment by Mikolaj** [comment]
Oh, indeed, https://www.haskell.org/cabal/download.html is one version behind.

**Comment by emilypi** [comment]
I'll get on this tonight, thanks for raising it

**Comment by Mikolaj** [comment]
Ping! :)

**Comment by Mikolaj** [comment]
@emilypi: may I help with that?

**Comment by jneira** [comment]
I hope a pr following https://github.com/haskell/cabal-website/pull/26/ would be welcomed

**Comment by Mikolaj** [comment]
@gbaz: this is fixed and merged. How do we publish?

**Comment by gbaz** [comment]
Contacted you via irc on how to upload to the website.

**Comment by Mikolaj** [comment]
@gbaz: thank you, done.

**Comment by Mikolaj** [comment]
And downloading `[cabal-install-3.6.2.0.tar.gz](https://downloads.haskell.org/~cabal/cabal-install-3.6.2.0/cabal-install-3.6.2.0.tar.gz)` finally works.
