### ISSUE TITLE
Stale link on www.haskell.org/cabal

### ISSUE THREAD

**Issue by hdgarrood** [haskell/cabal-website#3]
This page contains a link with text "Updating packages to work with recent Cabal and GHC versions." pointing to <http://haskell.org/haskellwiki/Upgrading_packages>, which only deals with GHC versions up to 7.0. The haskellwiki page does link to https://github.com/haskell-infra/hackage-trustees/blob/master/cookbook.md though - although that page seems to be almost entirely to do with errors introduced by lax/missing upper bounds, which doesn't seem to be quite the same thing to me. Perhaps this link should be updated or removed?

**Comment by 23Skidoo** [comment]
There is https://github.com/haskell/cabal/wiki/2.0-migration-guide, though it may be incomplete.

**Comment by hdgarrood** [comment]
Ah, thank you! This is the page I was looking for.

**Comment by hdgarrood** [comment]
Oh, I spoke too soon - I'm actually after some docs which tell me what (if anything) I should be aware of when updating to cabal-install >=2, i.e. as a Haskell package author, if I'm only using the command-line tool `cabal` and not the library. (The stale link probably wants addressing too, of course.)

**Comment by 23Skidoo** [comment]
Check out the [changelog](http://hackage.haskell.org/package/Cabal-2.0.0.2/changelog).

**Comment by Blaisorblade** [comment]
@hdgarrood A better changelog seems to be @23Skidoo's blog post: http://coldwa.st/e/blog/2017-09-09-Cabal-2-0.html — it seems rather good, just a bit hard to find unless you search /r/haskell on Reddit.

**Comment by 23Skidoo** [comment]
The Haskell wiki page seems to have been updated.
