### ISSUE TITLE
Homepage says that v2- commands are not yet default, but this is now false

### ISSUE THREAD

**Issue by fgaz** [haskell/cabal-website#6]
https://github.com/haskell/cabal-website/blob/cc824698a6eb6e9c52d95f60017db82a2fc4d2bf/index.html#L95

**Comment by cartazio** [comment]
@phadej @sclv @23Skidoo , whats the best way to address this and or who has the perms to do an update?

**Comment by 23Skidoo** [comment]
I do, you can make a PR for this repo.

**Comment by m-renaud** [comment]
@23Skidoo I've merged a PR to update the docs, can you publish the changes to the website? Thanks!

**Comment by 23Skidoo** [comment]
@m-renaud Done.
