### ISSUE TITLE
Redirect to cabal.readthedocs.io from haskell.org/cabal/users-guide

### ISSUE THREAD

**Issue by m-renaud** [haskell/cabal-website#8]
Currently there is no canonical website for the Cabal user guide. There is cabal.readthedocs.io which is where docs are automatically pushed whenever changes are made, and then there's haskell.org/cabal/users-guide which requires manually updating (which is bound to get out of date).

I propose we change haskell.org/cabal/users-guide to redirect to cabal.readthedocs.io. This will also help with SEO and ranking as there will be a single source of truth for the docs.

@23Skidoo wdyt?

**Comment by 23Skidoo** [comment]
SGTM, but will need coordination with @gbaz (or whoever has admin access to haskell.org) to set up redirects -- I don't think I can do it on my own.

Also: can we have a "stable" and "nightly" versions of readthedocs? IMO makes more sense for the default redirect to go to the former.

**Comment by m-renaud** [comment]
Yup! https://cabal.readthedocs.io/en/stable/

**Comment by simonmichael** [comment]
Ping @gbaz - are you the right person to help with this ?

Currently all cabal links on haskell.org lead to an old out of date cabal user guide, which is not at all obvious. This is a horrible user experience.

**Comment by gbaz** [comment]
ok redirect added.

**Comment by simonmichael** [comment]
Thanks @gbaz. I checked the following links, they work now thanks to the redirect, but could be updated to link directly:

- https://www.haskell.org/downloads/ -> "Cabal User Guide" and "The Cabal User Guide"
- https://www.haskell.org/documentation/ -> "Cabal User Guide"
- https://www.haskell.org/cabal/ -> "Getting Started", "User's Guide"

These links point to another location (https://downloads.haskell.org/~cabal/Cabal-latest) with out of date docs, they should be updated and perhaps that location should be deleted:

- https://www.haskell.org/cabal/download.html -> "User's guide" and "API Documentation"

**Comment by simonmichael** [comment]
Ping @gbaz, just in case you missed my reply above. The main points:

- two links are still leading to out of date docs and need fixing
- downloads.haskell.org/~cabal/Cabal-latest is still accessible and out of date, perhaps it should be retired ?
- five links are working thanks to the redirect, perhaps updating them to be direct links is better.

**Comment by gbaz** [comment]
I changed the redirect because I admin the server generally. I'm not the person to manage the textual content of the cabal website, including links.

**Comment by simonmichael** [comment]
Ok, thanks @gbaz. I think I'm in the right issue tracker and you closed this issue, so I pinged you again. I guess a new issue is the way to pursue this further.

**Comment by simonmichael** [comment]
Though, as server admin if you have any idea who's responsible for https://downloads.haskell.org/~cabal/Cabal-latest - not the content, but that general url - I'd appreciate it.

**Comment by simonmichael** [comment]
@gbaz, it seems the https://cabal.readthedocs.io/en/stable url [has been retired](https://github.com/haskell/cabal-website/pull/9#issuecomment-659506601), and https://cabal.readthedocs.io should be used instead. Would you mind updating the https://haskell.org/cabal/users-guide redirect once more.

**Comment by gbaz** [comment]
ok should be changed...

**Comment by simonmichael** [comment]
Looking good, thanks!
